apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager-sidecar
  namespace: monitoring
  labels:
    app: alertmanager-sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-sidecar
  template:
    metadata:
        labels:
          app: alertmanager-sidecar
    spec:
      serviceAccountName: alertmanager-sidecar
      containers:
      - name: alertmanager-sidecar
        image: "sysincz/sidecar:v0.4"
        ports:
        - containerPort: 2112
          name: metrics
        volumeMounts:
        - name: shared-volume
          mountPath: /etc/config/
        - name: config-volume
          mountPath: /config
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
      volumes:
      - name: shared-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          name: alertmanager-sidecar-config
