---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: alertmanager-sidecar-clusterrolebind
roleRef:
  kind: ClusterRole
  name: alertmanager-sidecar-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: alertmanager-sidecar
  namespace: monitoring