---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-sidecar
  namespace: "monitoring"
  labels:
    app: alertmanager-sidecar
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    app: alertmanager-sidecar