---
apiVersion: v1
kind: Service
metadata:
  name: msteams-sidecar
  namespace: "monitoring"
  labels:
    app: mstaeams-sidecar
    monitoring: "true"
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 2112
      targetPort: metrics
      protocol: TCP
  selector:
    app: prometheus-msteams
